name: Publish new version on PyPi

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: Version bump!
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PYPI_PUBLISH_PAT }}
          fetch-depth: 0
          ref: master

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Deps
        run: pip install --upgrade twine wheel

      - name: Set Version in version.py
        run: echo "__version__ = '${{ github.events.inputs.version }}'" > honeybadger/version.py

      - name: Git Config
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Update changelog
        run: |
          sed '6 a ## [0.9.0] - 2022-08-18' CHANGELOG.md
          sed '6 a  ' CHANGELOG.md

      - name: Push version on git
        run: |
          git commit -m "Release ${{ github.events.inputs.version }}"
          git tag v${{ github.events.inputs.version }}
          git push origin master --tags

      - name: Build
        run: python setup.py bdist_wheel

      - name: Upload
        run: twine upload -u ${{ secrets.PYPI_USERNAME }} -p ${{ secrets.PYPI_PASSWORD }} --non-interactive dist/*
